### PR TITLE
Readme: AWS SES email notifications

### PR DESCRIPTION
**Pull request by sergeyph**
Added AWS SES email notifications setup instructions

### CODE REVIEW

**Review by aonnikov — APPROVED** [review]

**Comment by aonnikov** [comment]
@sergeyph thanks for the contribution. The changes look good to me, but could you please resolve merge conflict when you have a chance?

**Comment by sergeyph** [comment]
> @sergeyph thanks for the contribution. The changes look good to me, but could you please resolve merge conflict when you have a chance?

Resolved in main

**Comment by pathros** [comment]
How do you set SMTP up other than Amazon?

**Comment by sergeyph** [comment]
> How do you set SMTP up other than Amazon's?

I don't know if they have SMTP. You can try support via slack channel.

**Pull request merged**
