### PR TITLE
Nginx config to run Huly on one domain name

### PR DESCRIPTION
**Pull request by egavrilov**
Hey
Created some simple Nginx config to start Huly on one domain name without need to setup subdomains, CORS and websockets.

- Config is generated through `setup.sh`
- User could choose between ssl (https/wss) and non-ssl configuration
- Websockets are working correctly through Nginx

SSL should be configured separately

If you already have Nginx with certificates manager set up on your host simply add a config and point to exposed port from the docker compose.
For example:

```
server {
    listen 443;
    server_name ${your domain};

   location / {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_pass http://localhost:${EXPOSED_NGINX_PORT};
    }
}
```

### CODE REVIEW

**Comment by aonnikov** [comment]
Hey! Thanks for the contribution, looks good to me

**Comment by veryCrunchy** [comment]
The concept behind this PR is solid, and the initial execution looks good at a glance. However, it seems clear that the code hasn't been tested thoroughly, if at all. @aonnikov, I would strongly encourage ensuring proper testing is done before approving PRs in the future, as it helps avoid issues down the line.

For example, after trying to self-host Huly using this PR's implementation, issues quickly start to surface. One of the many clear indicators that the code hasn't been tested is the following configuration:

```nginx
location /_reconi {
    ...
    proxy_pass http://reconi:4004/;
}
```

There is no container named `reconi`, and nothing would attempt to access this path, as the service is named `rekoni`. This simple oversight could have been caught with basic testing.

**Comment by egavrilov** [comment]
@veryCrunchy good point, mate! Despite the typo Huly is working for task management and I didn't find any issues. It might be that rekoni is mainly called through internal endpoint.
Thanks for the fix, tho!

**Comment by aonnikov** [comment]
> The concept behind this PR is solid, and the initial execution looks good at a glance. However, it seems clear that the code hasn't been tested thoroughly, if at all. @aonnikov, I would strongly encourage ensuring proper testing is done before approving PRs in the future, as it helps avoid issues down the line.
> 
> For example, after trying to self-host Huly using this PR's implementation, issues quickly start to surface. One of the many clear indicators that the code hasn't been tested is the following configuration:
> 
> ```nginx
> location /_reconi {
>     ...
>     proxy_pass http://reconi:4004/;
> }
> ```
> 
> There is no container named `reconi`, and nothing would attempt to access this path, as the service is named `rekoni`. This simple oversight could have been caught with basic testing.

Nice catch! And thanks for the fix.

**Pull request merged**
